services:
  hsl:
    image: home-services-logbook:dev
    build:
      context: .
    container_name: hsl
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - hsl_data:/data
    restart: unless-stopped

volumes:
  hsl_data: